accelerate launch --multi_gpu --mixed_precision=fp16 --num_processes=2  refl_lora.py \
  --resolution=512 --center_crop --random_flip \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 \
  --gradient_checkpointing \
  --max_train_steps=100 \
  --learning_rate=1e-04 \
  --max_grad_norm=1 \
  --lr_scheduler="constant" --lr_warmup_steps=0 \
  --output_dir="checkpoint/refl_lora" \
  --grad_scale 0.01 \
  --checkpointing_steps 100
